Repository MonAPI-xyz/MonAPI, pull requests merged in 2022-11, with the labels that each got.

#70 feat: Release 3 - 31 October 2022
  .env.example
  README.md
  alerts/__init__.py
  alerts/admin.py
  alerts/apps.py
  alerts/models.py
  alerts/serializers.py
  alerts/tests.py
  alerts/urls.py
  alerts/views.py
  apimonitor/admin.py
  apimonitor/migrations/0005_apimonitor_assertion_value_apimonitor_assetion_type_and_more.py
  apimonitor/migrations/0006_apimonitor_is_assert_json_schema_only_and_more.py
  apimonitor/migrations/0007_rename_assetion_type_apimonitor_assertion_type.py
  apimonitor/migrations/0008_alter_assertionexcludekey_monitor.py
  apimonitor/migrations/0009_alertsconfiguration_email_use_ssl_and_more.py
  apimonitor/migrations/0010_alertsconfiguration_threshold_pct_and_more.py
  apimonitor/models.py
  apimonitor/serializers.py
  apimonitor/tests.py
  apimonitor/urls.py
  apimonitor/views.py
  cron/management/commands/run_cron.py
  cron/tests.py
  docs/release_notes.md
  error_logs/tests.py
  monapi/settings.py
  monapi/urls.py
  requirements.txt
  utils.py
Labels: release

#73 feat: PBI-20-Integrate Alerts Email-Backend
  alerts/management/commands/run_cron_alerts.py
  alerts/serializers.py
  alerts/tests.py
  apimonitor/migrations/0012_alertsconfiguration_email_address_and_more.py
  apimonitor/models.py
  template/email/alerts.html
Labels: feature

#76 chores: refactor environment variable between frontend url and cors allowed origins
  .env.example
  monapi/settings.py
Labels: config
